### ISSUE TITLE
Diabetes by year and CCG per list size

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/prescribing-queries#1]
> You have some very helpful data on the diabetes drug spend by CCG, but I wondered whether you had this available in an excel version rather than images? I’m particularly interested in the total 2015 and 2016 diabetes drug spend by CCG rather than monthly.
> 
>  ...This is the link I was searching on the site https://openprescribing.net/analyse/#org=CCG&numIds=6.1&denom=total_list_size&selectedTab=summary

**Comment by sebbacon** [comment]
So the following query is based on these assumptions (many of which haven't been specified by the requestor):
- Numerator: sum of actual_cost
  - Numerator condition: where bnf_code starts with 0601
- Denominator: total list size
  - Denominator condition: the largest the practice list was in any given year
- Group by: year, ccg
- Only include standard GP practices

So we might want to check with them that they want actual_cost, standard GP practices, and the largest a practice was in a given year.  

``` sql
SELECT
  ccg_id,
  year,
  SUM(numerator) AS numerator,
  SUM(denominator) AS denominator,
  -- IEEE_DIVIDE doesn't complain about dividing by zero
  IEEE_DIVIDE(SUM(numerator), SUM(denominator)) AS calc_value
FROM (
  SELECT
    *
  FROM (
    SELECT
      COALESCE(num.numerator,
        0) AS numerator,
      COALESCE(denom.denominator,
        0) AS denominator,
      practices_with_year.practice_id,
      practices_with_year.ccg_id AS ccg_id,
      practices_with_year.year
    FROM (
      SELECT
        EXTRACT(YEAR
        FROM
          month) AS year,
        practice,
        SUM(actual_cost) AS numerator
      FROM
        ebmdatalab.hscic.prescribing
      WHERE
        bnf_code LIKE '0601%'
      GROUP BY
        practice,
        year) num
    RIGHT JOIN (
      -- We use a right join to ensure we always get a denominator value for every practice, even when not prescribing
      SELECT
        EXTRACT(YEAR
        FROM
          month) AS year,
        practice,
        -- Here we assume they want the largest a practice was in a given year
        MAX(total_list_size) AS denominator
      FROM
        ebmdatalab.hscic.practice_statistics
      GROUP BY
        year,
        practice ) denom
    ON
      (num.practice=denom.practice
        AND num.year=denom.year)
    RIGHT JOIN (
        -- Return a row for every practice in every year, even where
        -- there is no denominator value
      SELECT
        prescribing.year AS year,
        practices.code AS practice_id,
        ccg_id
      FROM
        `ebmdatalab.hscic.practices` AS practices
      CROSS JOIN (
        -- It's the cross join that ensures a year for every practice
        SELECT
          EXTRACT(YEAR
          FROM
            month) AS year
        FROM
          ebmdatalab.hscic.prescribing
        GROUP BY
          year) prescribing
      WHERE
        practices.setting = 4) practices_with_year
    ON
      practices_with_year.practice_id = num.practice
      AND practices_with_year.year = num.year ) )
GROUP BY
  ccg_id,
  year
ORDER BY
  ccg_id,
  year
```

**Comment by annapowellsmith** [comment]
I think I'd do it more simply, at least initially:

```
SELECT
  pct AS ccg,
  SUM(items) AS items,
  SUM(actual_cost) AS actual_cost
FROM
  [ebmdatalab:hscic.prescribing]
WHERE
  bnf_code LIKE '0601%'
  AND month BETWEEN TIMESTAMP('2015-01-01')
  AND TIMESTAMP('2015-12-01')
GROUP BY
  ccg
ORDER BY
  ccg
```

That's based on the assumption that she just wants the raw numbers by CCG for 6.1 for 2015 by CCG, exactly as presented in the prescribing dataset.

If she wants more than that, I think we should open a conversation about citations etc.

**Comment by annapowellsmith** [comment]
Also fwiw: I wouldn't assume that we would exclude non-standard practices, since she's interested in spending by CCG.

**Comment by sebbacon** [comment]
Regarding citations: I think we should be having that conversation anyway, even if we do the simpler thing.  We need to have a think about how we can enforce it -- probably by saying "if we help you, the deal is we get a citation and a view on the work you produce -- is that OK?" and then setting a calendar reminder to follow up once a month until they show it us?

**Comment by annapowellsmith** [comment]
Yes agree! I think just asking people when we send the initial data is probably good enough, but that's one for Ben to decide.

**Comment by sebbacon** [comment]
Incidentally, if she does want it restricted to standard GP practices then a version of Anna's query would be:

``` sql
SELECT
  month,
  pct AS ccg,
  SUM(items) AS items,
  SUM(actual_cost) AS actual_cost
FROM
  ebmdatalab.hscic.prescribing
RIGHT JOIN
  ebmdatalab.hscic.practices AS practices
ON
  practices.code = practice
  AND practices.setting = 4
WHERE
  bnf_code LIKE '0601%'
  AND month BETWEEN TIMESTAMP('2015-01-01')
  AND TIMESTAMP('2015-12-01')
GROUP BY
  month, ccg
ORDER BY
  month, ccg
```

(Note I also added in the months -- then she can join the data together by FY or whatever as she likes)

**Comment by lmfrench** [comment]
We will need to extend the months if we want to include FY, I did try & clarify about whether she wanted FY to start with, and she did say calendar year

``` sql
SELECT
  pct AS CCG,
  name AS CCG_Name,
  SUM(items) AS items,
  SUM(actual_cost) AS actual_cost


FROM
  ebmdatalab.hscic.prescribing AS presc

LEFT JOIN ebmdatalab.hscic.eccg AS eccg
  ON (org_code=presc.pct)


  WHERE
bnf_code LIKE '0601%' AND
 (month BETWEEN TIMESTAMP('2015-01-01') AND TIMESTAMP('2015-12-31'))

GROUP BY
 CCG_Name,
 CCG

ORDER BY
  CCG
```

She also asked for total prescribing costs:

``` sql
SELECT
  pct AS CCG,
  name AS CCG_Name,
  SUM(items) AS items,
  SUM(actual_cost) AS actual_cost


FROM
  ebmdatalab.hscic.prescribing AS presc

LEFT JOIN ebmdatalab.hscic.eccg AS eccg
  ON (org_code=presc.pct)


  WHERE

 (month BETWEEN TIMESTAMP('2015-01-01') AND TIMESTAMP('2015-12-31'))

GROUP BY
 CCG_Name,
 CCG

ORDER BY
  CCG

```

**Comment by lmfrench** [comment]
Will add 'do you want to see actual cost?' and 'do you want to see only standard GP practices?' to the list of clarifying questions for future queries

**Comment by sebbacon** [comment]
Observations:
1. The eccg table may not have been updated for some time -- I've not been using it recently. However, I _think_ the CCG list hasn't changed since 2013.
2. The prose suggests you intended to do two different queries, but you've pasted two identical ones?

**Comment by lmfrench** [comment]
Have edited my post sorry!

**Comment by sebbacon** [comment]
Nope, still don't get it!

They're now different, but both sum the total costs, the first for everything and the second for a BNF chapter..?

**Comment by lmfrench** [comment]
ok fixed - they are almost identical, the top one should have the BNF chapter, second one shouldn't

**Comment by lmfrench** [comment]
For context, follow up email said:
'Total diabetes drugs spend by each CCG is great, and if possible, the % of diabetes drugs by CCG against their total drugs spend/total drug allocation.' with a screenshot showing a column for 'Total Diabetes Drug Spend' and another 'Total Drug Spend' which she wanted to populate. First query gets the diabetes drug spend, second the total

**Comment by sebbacon** [comment]
:+1: looks good
