### ISSUE TITLE
How can I group together generic presentations with branded equivalents?

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/prescribing-queries#19]
```sql
SELECT
  practice,
  pct,
  bnf_code,
  IF(LENGTH(RTRIM(bnf_code)) >=15, SUBSTR(bnf_code, 10, 2) = 'AA', NULL) AS is_generic,
  IF((LENGTH(RTRIM(bnf_code)) = 15
      AND SUBSTR(bnf_code, 14, 2) != 'A0'), CONCAT(SUBSTR(bnf_code, 1, 9), 'AA', SUBSTR(bnf_code, 14, 2), SUBSTR(bnf_code, 14, 2)), bnf_code) AS generic_presentation,
  actual_cost,
  quantity
FROM
  ebmdatalab.hscic.prescribing
LIMIT
  100
```

Notes: 
 * `is_generic` field isn't necessary for this example, but demonstrates how to select only generic codes (in this case it creates a field with `true` or `false` values
* the logic of `generic_presentation` is that only 15 character bnf_codes without `A0` at positions 14 and 15 can have a generic equivalent. Codes with no generic equivalent are emitted unchanged for that column.
* we have to `RTRIM` the `bnf_code` field because at present (Dec 2016) the field always has spaces to fill out to 15 characters on the right hand side

See [this diagram](../blob/master/bnf_code_understander.png) to help understand BNF codes

**Comment by HelenCEBM** [comment]
should line 6 read : 
```  IF(SUBSTR(bnf_code, 14, 2) != 'A0',```
?

**Comment by sebbacon** [comment]
Yes it should! Will fix.
