### ISSUE TITLE
Levothyrox/Liothronine by month & by CCG

### ISSUE THREAD

**Issue by lmfrench** [ebmdatalab/prescribing-queries#2]
I'd very much like to know the makes of the various Levothyrox/Liothyronine products that have been prescribed. Is that available? Oh - and including number of prescriptions of each manufacturer/tablet - ideally by CCG.
...
It would be great to have it by month over past year or two

**Comment by lmfrench** [comment]
Assumptions for this query:
- Actual Cost
- Include all GP practices

We also need to consider how the BNF classifies generic/brand, as I don't think our assumption that 'AA' at the end = generic is correct. This [blog](https://scraperwiki.com/2015/08/gp-prescribing-data-for-the-uk/) has more information (but does not link to a source):
• 12 & 13 indicate the Strength and Formulation (AD)
• 14 & 15 show the equivalent (AD). The ‘equivalent’ is defined as follows:
o   If the presentation is a generic, the 14th and 15th character will be the same as the 12th and 13th character.
o   Where the product is a brand the 14 and 15 digit will match that of the generic equivalent, unless the brand does not have a generic equivalent in which case A0 will be used.

``` sql
SELECT 
  PCT AS CCG, 
  name AS CCG_Name,
  STRFTIME_UTC_USEC(TIMESTAMP(month),'%B %Y') AS Month, 
  bnf_code AS BNF_Code, 
  bnf_name AS BNF_Name, 
  CASE
    WHEN SUBSTR(bnf_code,14) LIKE 'AA' THEN 'Generic'
    ELSE 'Brand'
  END AS Generic,
  SUM(items) as Items, 
  SUM(actual_cost) as Actual_Cost
FROM ebmdatalab.hscic.prescribing AS presc

LEFT JOIN ebmdatalab.hscic.eccg AS eccg
  ON (org_code=presc.pct)

WHERE 
  TIMESTAMP(month)>=TIMESTAMP('2014-01-01')
  AND
  bnf_code LIKE '0602010Z0%'

GROUP BY
  CCG,
  CCG_Name,
  month,
  bnf_code,
  generic,
  bnf_name
```

**Comment by annapowellsmith** [comment]
According to the BSA it's the 10th and 11th characters that indicate if a product is generic (see email thread I have just forwarded). If these characters are `AA` then the product is generic, if they are anything else then it isn't. I think the post above is explaining how to find the generic equivalent of branded presentations, which is slightly different.

**Comment by annapowellsmith** [comment]
All looks good otherwise - though as mentioned I would make the column names lowercase, and not cast the timestamp to a string. 👍

**Comment by lmfrench** [comment]
Ok fixed, thanks

``` sql
SELECT 
  PCT AS CCG, 
  name AS CCG_Name,
  TIMESTAMP(month) AS month, 
  bnf_code AS BNF_Code, 
  bnf_name AS BNF_Name, 
  CASE
    WHEN SUBSTR(bnf_code,10) LIKE 'AA' THEN 'Generic'
    ELSE 'Brand'
  END AS generic,
  SUM(items) as items, 
  SUM(actual_cost) as actual_cost
FROM ebmdatalab.hscic.prescribing AS presc

LEFT JOIN ebmdatalab.hscic.eccg AS eccg
  ON (org_code=presc.pct)

WHERE 
  TIMESTAMP(month)>=TIMESTAMP('2014-01-01')
  AND
  bnf_code LIKE '0602010Z0%'

GROUP BY
  CCG,
  CCG_Name,
  month,
  bnf_code,
  generic,
  bnf_name
```

**Comment by annapowellsmith** [comment]
looks good to me!

**Comment by lmfrench** [comment]
Have changed the case statement to:

``` sql
 CASE
    WHEN SUBSTR(bnf_code,10,2) LIKE 'AA' THEN 'Generic'
    ELSE 'Brand'
  END AS type,
```

(checked it with Richard & it wasn't correctly classifying brand/generic, looks like it is working now).

Other thing Richard pointed out - we are currently only searching for the combination product - Levothyrox/Liothronine - but there are products for each separate chemical. For this query, I'm going to send it out only with the combination product & ask them to come back to us if they want the separate ones, but it is another question to add to the list for future queries!

**Comment by annapowellsmith** [comment]
Oh, duh sorry, I realised `SUBSTR(bnf_code,10)` would give you a six-letter code, but didn't spot the `LIKE 'AA'`, which of course would have to be `LIKE 'AA%'` to match a six-letter code. In generally it is probably safer to use `=` rather than `LIKE` if that is what you intend!

**Comment by lmfrench** [comment]
Ah yeah I see, forgot the wildcard! Although I think the way I've done it now still works. Have changed it to =, this query is from before you mentioned that :) 

So final query used:

``` sql
SELECT 
  PCT AS CCG, 
  name AS CCG_Name,
  STRFTIME_UTC_USEC(TIMESTAMP(month),'%Y-%m') AS month,
  bnf_code AS BNF_Code, 
  bnf_name AS BNF_Name, 
  CASE
    WHEN SUBSTR(bnf_code,10,2) = 'AA' THEN 'Generic'
    ELSE 'Brand'
  END AS type,
  SUM(items) as items, 
  SUM(actual_cost) as actual_cost
FROM ebmdatalab.hscic.prescribing AS presc

LEFT JOIN ebmdatalab.hscic.eccg AS eccg
  ON (org_code=presc.pct)

WHERE 
  TIMESTAMP(month)>=TIMESTAMP('2014-01-01')
  AND
  bnf_code LIKE '0602010Z0%'

GROUP BY
  CCG,
  CCG_Name,
  month,
  bnf_code,
  type,
  bnf_name

 ORDER BY
  month,
  CCG_Name
```

**Comment by annapowellsmith** [comment]
👍
