### ISSUE TITLE
How do I restrict my searches to standard GP practices only?

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/prescribing-queries#21]
You have to join on ebmdatalab.hscic.practices and restrict the results to only those practices with a `setting` of 4.  The full list of settings is documented in the [README](../blob/master/README.md)

```sql
SELECT
  *
FROM
  ebmdatalab.hscic.prescribing AS prescribing
JOIN
  ebmdatalab.hscic.practices practices
ON
  practices.code = prescribing.practice
  AND practices.setting = 4
WHERE
  bnf_code = '0408010AEAAACAC'
  AND month = '2016-08-01'
LIMIT
  10
```

**Comment by HelenCEBM** [comment]
should this be a right join as well?

**Comment by sebbacon** [comment]
Or an inner join - fixed, thanks
