### ISSUE TITLE
How can we compare equivalent products which don't have generic equivalents coded?

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/prescribing-queries#29]
There are over 1000 products without a generic equivalent listed in the BNF (identified by codes ending in `A0`).

Some of these *can* be meaningfully compared with each other, despite not having a formally coded generic equivalent. For example, Blood Glucose Test Strips are clinically equivalent, but are coded as `A0`.  In this case, we can group them together by BNF subparagraph -- everything within `0601060D0%` is a blood glucose test strip, and we believe that the `quantity` field consistently refers to number of strips.

We need to come up with a list of products without generic equivalents which we can add as special cases to the code that computes price-per-pill variability.

As these are all special cases, and we might not be able to solve them all with the "subparagraph" trick that applies to BGTS, we may need to prioritise only the ones with higher spending.

The approach discussed is to 
* make a list of `A0` products ordered by total spend ([here](https://docs.google.com/spreadsheets/d/1zAeZJhVz9FNtO5WDTocaRIbNkeLIX1AssA6svJ-gMDQ)
* exclude foods from the list
* pick an arbitrary cut-off point below which we don't care about (e.g. £20k per month?)
* for products above that point, pick things where we think meaningful comparisons could be made, and record here (with reasons)

An example of a product we don't think we can handle is ThickenUp cream -- because it is recorded (like glycopyrronium) inconsistently in quantities of 1 (box) or 75 (sachets in a box).  See [this analysis](https://github.com/ebmdatalab/tariff-data/blob/master/Drug%20price%20variance.ipynb) for a discussion

**Comment by richiecroker** [comment]
Looking further into it, i think that we are going struggle with dermatological preparations.  E.g. Aveeno cream, where [BNF prices state](https://www.evidence.nhs.uk/formulary/bnf/current/13-skin/132-emollient-and-barrier-preparations/1321-emollients/proprietary-emollient-preparations/aveeno):
Cream, colloidal oatmeal in emollient basis, net price 100 mL = £3.97, 300-mL pump pack = £6.80

So NIC per quantity for 100ml is 3.97p per ml, for 300ml is 2.27p per ml.  We have no way of knowing what the split is.

**Comment by sebbacon** [comment]
Can you paste a link to the google sheet we were looking at?

**Comment by richiecroker** [comment]
https://docs.google.com/spreadsheets/d/1zAeZJhVz9FNtO5WDTocaRIbNkeLIX1AssA6svJ-gMDQ/edit#gid=516207808

**Comment by richiecroker** [comment]
This is also interesting - shows the problem with Aveeno cream as an example
https://docs.google.com/spreadsheets/d/1GNzV6BgS4tpFn4fOsR_WrXvnYblPvSDzHN0eRdMpJsU/edit#gid=717497589

**Comment by sebbacon** [comment]
# Ideal scenario

In an ideal world, when considering which A0 (non-generic) presentations we want to consider for special-casing, we would filter out those that don't have a strong unimodal distribution.  In fact, I'd go further and say we probably want to filter out any branded presentations that don't fit this criterion across the entire dataset.

As discussed, Glycopyrrunium Bronchodilators and ThickenUp are examples of non-unimodal distributions of price-per-quantity, graphed in [this analysis](https://github.com/ebmdatalab/tariff-data/blob/master/Drug%20price%20variance.ipynb).

In the former case, we know that this is a special case where it is only allowed to be dispensed in multiples of 30. We have further established that if it's recorded as 1 or 30 in our data seems to depend on GP software, at least some of which corrects the rx to 30 when they enter the number 1; but not if they prescribe generically.

A new example is one of the reagent strips, CoaguChek XS PT Strips, which otherwise, as a class, seem very reliably coded. However, it is clearly bimodal:

![image](https://cloud.githubusercontent.com/assets/211271/21014641/c16f1c2a-bd56-11e6-89cd-fa14c7a2f5b5.png)

Based off that graph's two modes, we can categorise all prescriptions as belonging to the left or right side:

```sql 
SELECT
  SUM(items) AS items,
  SUM(quantity) AS quantity,
  SUM(quantity)/SUM(items) AS qpi,
  IF(net_cost/quantity < 2.85, 'low', 'high') AS category
FROM
  ebmdatalab.hscic.prescribing
WHERE
  bnf_code = '0208020W0BBABA0'
  AND month = TIMESTAMP('2016-09-01')
GROUP BY
  category
```

This suggests that the product probably comes in packs of 24 and 48:

![image](https://cloud.githubusercontent.com/assets/211271/21014713/fdb4ab00-bd56-11e6-94da-66a2fa0a7c16.png)

A [google images search for the product name](https://www.google.co.uk/search?q=CoaguChek+XS+PT+Strips&&tbm=isch) confirms the hypothesis.

By contrast, the kind of product we could use as a basis for comparisons has a price per quantity distribution similar to this:

![image](https://cloud.githubusercontent.com/assets/211271/21014840/6ea2a7b8-bd57-11e6-9a49-fcb5d0f1a189.png)

(This is Dermol 600 Bath Emollient)

I've had a look at Hartigans' Dip Test Statistic for Unimodality, but that fails for cases like the Dermol ointment, perhaps because it does have the inevitable odd outlier, making the overall distribution non-normal? There are many other possible tests but an expert eye would be useful. *Can we ask a statistician for ideas about how we could detect this automatically?*

# Compromise way forward

The vast majority of A0 presentations that look promising from eyeballing them are those in 
* Urine Testing Reagents (0601060U0%) and 
* Glucose Blood Testing Reagents (0601060D0%)

On the whole, it seems like the following tend to have high incidence of multiple-pack-sizes:

* Nutrition (evertying in Chaper 0905)
* Foods (evertying in Chaper 0904)
* Compound Vit/Mineral Formulations (0910)
* Other drugs and preparitions (19)

It also looks a bit like the following are also in inconsistent pack sizes:

* Anything with "Preparations" in the section or subsection, e.g. 
  * Compound Alginates&Prop Indigestion Prep
  * Preparations used in Diagnosis (18)
  * Skin > Miscellaneous Topical Preparations (1315)
  * Other Aural Preparations (120101020)

As a counter example to this suggested approach, Dermol Cream (which would be excluded per these rules) has a high monthly spend £275,960) and is unimodal, but on its own it is probably not worth looking at, given other presentations in its class exhibit the multimodal problem too. 

@richiecroker, What do you think about the above rough sketch? Does what I've observed about "Preparations" make any sense, or am I seeing a pattern where there isn't one?

**Comment by sebbacon** [comment]
Closing in favour of https://github.com/ebmdatalab/price-per-dose/issues/1 and https://github.com/ebmdatalab/price-per-dose/issues/2
