### ISSUE TITLE
Flixotide Evohalers by month and by CCG

### ISSUE THREAD

**Issue by lmfrench** [ebmdatalab/prescribing-queries#3]
I was trying to look up the expenditure on Flixotide Evohaler 50mcg, 125mcg and 250mcg by CCG 
...
https://openprescribing.net/analyse/#org=CCG&numIds=0302000N0BBAXBA,0302000N0BBAZBC,0302000N0BBBBBH&denom=total_list_size&selectedTab=summary 
2014-now would be great

**Comment by lmfrench** [comment]
Assumptions made:
User doesn't want vs list size, and is using this because there is no option to leave the denominator blank
Actual Cost wanted
All GP Practices included

Can't export this to csv:
Error message: 'This result set contains too many rows to download. Please use "Save as Table" and then export the resulting table.'

``` sql
SELECT 
PCT AS CCG, 
name AS CCG_Name,
STRFTIME_UTC_USEC(TIMESTAMP(month),'%B %Y') AS Month, 
bnf_code AS BNF_Code, 
bnf_name AS BNF_Name, 
SUM(items) as Items, 
SUM(actual_cost) as Actual_Cost 
FROM ebmdatalab.hscic.prescribing AS presc

LEFT JOIN ebmdatalab.hscic.eccg AS eccg
  ON (org_code=presc.pct)
WHERE 
TIMESTAMP(month)>=TIMESTAMP('2014-01-01')
AND
(bnf_code LIKE '0302000N0BBAXBA' OR bnf_code LIKE '0302000N0BBAZBC' OR bnf_code LIKE '0302000N0BBBBBH')
GROUP BY
CCG,
CCG_Name,
month,
bnf_code,
bnf_name
```

**Comment by annapowellsmith** [comment]
sigh. I'd actually go back to the user and confirm whether they want it broken down by month, or whether they just want total spending from 2014 to now. if the former then we have to export the table, which i can show you how to do.

**Comment by lmfrench** [comment]
That is now on my list of questions to clarify with users, but wasn't asked of this person. I think in future that should be asked but for this user I think I can give it them by month & they can combine it themselves if they want to?

**Comment by lmfrench** [comment]
Sorry - ignore, I forgot this was the one I couldn't export the table with! Will check with them

**Comment by lmfrench** [comment]
closed - user never got back to us
