### ISSUE TITLE
How come so many Category C drugs are showing potential cost savings?

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/prescribing-queries#30]
For example, the cost-per-dose of Budesonide/Formoterol Inh (0302000K0AAAMAM) in Rich's practice is £33.79; the price at the 10th decile in £27.77.  The tariff price was £38. Jupyter notebook [here](https://github.com/ebmdatalab/price-per-dose/blob/2afea900925cec5baeba8b86d08d3dd6e08f99dd/Price%20per%20dose.ipynb).

If we drill down into the data, we see that in fact the inhaler has been prescribed once by brand name and in that instance it was very cheap.  In all other cases it was prescribed generically.

```sql
SELECT
  p.bnf_name,
  t.category,
  quantity,
  net_cost,
  actual_cost/quantity AS ppq
FROM
  ebmdatalab.hscic.prescribing AS p
LEFT JOIN
  ebmdatalab.hscic.tariff t
ON
  t.bnf_code = p.bnf_code
  AND TIMESTAMP(t.date) = p.month
WHERE
  p.month = '2016-09-01'
  AND p.bnf_code LIKE '0302000K0__AM%'
ORDER BY
  ppq
```

![image](https://cloud.githubusercontent.com/assets/211271/21051194/fc9a969c-be16-11e6-8973-12ca4ec4fd67.png)

If we were to exclude that single abnormally-low prescription, the price at the 10th decile would be £35.21, changing Richard's relative loss to a profit.

**Comment by sebbacon** [comment]
OK, two characters wrong in the BNF code makes this entire analysis wrong!

The truth is that there are actually 2 brands of this inhaler - Symbicort and DuoResp.  The former costs £35 and the latter £27.

I think the problem is a misunderstanding of Category C. Category C is not always drugs under patent. It is simply drugs where the tariff is based on the price of one available drug.

**Comment by richiecroker** [comment]
The code is wrong in the SQL above: it's picking up drugs are are not the same. It picked up Pulmicort_Inhaler, which is 
```sql
'0302000K0BBAMAZ'
```

It needs to be:
```sql
AND p.bnf_code LIKE '0302000K0%AM'
```
