### ISSUE TITLE
Specials in Calderdale &  Bradford CCGs

### ISSUE THREAD

**Issue by lmfrench** [ebmdatalab/prescribing-queries#48]
BNF codes: there are no specific specials that I need data for
CCG/GP Practice(s): Calderdale CCG, Bradford Districts CCG and Bradford City CCG 
Grouped by CCG or GP Practice: GP practice please 
Time period: March and April 2017 
Grouped monthly/yearly: Monthly 
The prescribing dataset includes prescribing from non-standard GP Practices - for example, out of hours and walk in centres. Do you want the data from these practices to be excluded from your extract? Yes please 

Discussion with Seb & Rich: 
- is_special flag in dm&d
- Anything with Spec in name
- specials section in ePACT (list in slack)

User is aware the list may not be comprehensive

**Comment by lmfrench** [comment]
is_special flag in dm+d is found by following SQL:

```sql
SELECT
  *
FROM
  ebmdatalab.hscic.dmd
WHERE
  avail_restrictcd = '6'
```

I compared this list to the ePACT list @richiecroker shared in Slack

There were 921 items that appeared in ePACT and not in dm+d. 
- Most of these items don't have a dm+d code. 
- 111 items do have a dm+d code, but aren't flagged as a special

**Comment by lmfrench** [comment]
I've done a search in the prescribing table
```sql
SELECT 
  presc.bnf_code,
  presc.bnf_name
  FROM 
  ebmdatalab.hscic.normalised_prescribing_standard AS presc


WHERE
bnf_name LIKE "% Spec %"
GROUP BY
bnf_code,
bnf_name
```
There are only a few results which don't appear in either the ePACT list or the dm+d flag list. These are: 

0410000M0AAAMAM | Methadone HCl_Liq Spec 50mg/5ml
0410000M0AAAQAQ | Methadone HCl_Liq Spec 10mg/5ml
0410000M0AAARAR | Methadone HCl_Liq Spec 25mg/5ml
0410000M0AAAUAU | Methadone HCl_Liq Spec 1mg/5ml
0410000M0AABEBE | Methadone HCl_Liq Spec 100mg/5ml
0410000M0AABFBF | Methadone HCl_Liq Spec 12.5mg/5ml
0410000M0AABKBK | Methadone HCl_Liq Spec 4.71mg/5ml
0410000N0AAACAC | Naltrexone HCl_Liq Spec 12.5mg/5ml
0410000N0AAAHAH | Naltrexone HCl_Liq Spec 3mg/5ml
0410000N0AAAJAJ | Naltrexone HCl_Liq Spec 1mg/5ml
0410000N0AAARAR | Naltrexone HCl_Liq Spec 5mg/5ml
130501000BBBAA0 | Elena's_Day Crm Spec

There are also a few trusses that I don't think should be included (e.g. Elas Band Inguinal Spec Sle Truss)

**Comment by lmfrench** [comment]
If you search in the bnf table instead of the prescribing table you find a different list of specials that aren't in dm+d or ePACT
```sql
SELECT 
  presentation_code,
  presentation

  FROM 
  ebmdatalab.hscic.bnf AS bnf

WHERE presentation LIKE "% Spec %"
GROUP BY
presentation_code,
  presentation
```
List with Trusses removed:
091200000BBBKA0 | Blakoe_Ladies Spec For Tab
091101000BBSZDJ | Amargine_Liq Spec 500mg/5ml
130201000BBHAA0 | Natur Flow_Very Spec Vit E Crm
0301030S0AABCBC | Theophylline_Liq Spec 60mg/5ml
090401000AAAXAX | Gppe Milk Food_Milupa Spec Hn25
0407020Q0AAFMFM | Morph Sulf_Gel Spec 1% 10ml Pfs
0401020K0AABHBH | Diazepam_Liq Spec 10mg/5ml (Old)
190202000AABBBB | Individually Formulated Spec CD_
21050000226 | Payne_Suprapubic Spec Kipper Bag
0407010H0AAAVAV | Paracet_Tab Spec Fine Grade 500mg
090900000BBDQA0 | Milupa_Cauliflower Cheese Spec Infant Fo
22300103016 | Hollister_InView Incont Sheath Self-Adh Spec 25mm
22300103017 | Hollister_InView Incont Sheath Self-Adh Spec 29mm
22300103018 | Hollister_InView Incont Sheath Self-Adh Spec 32mm
22300103019 | Hollister_InView Incont Sheath Self-Adh Spec 36mm
22300103020 | Hollister_InView Incont Sheath Self-Adh Spec 41mm
21090000390 | Spec Sanction App_Robinson's Spec Fine Non-Absorb
21010900595 | Autopen Spec Edition Pen 3ml 1u (1-21u) Hypod Reusable Pen
21010900596 | Autopen Spec Edition Pen 3ml 2u (2-42u) Hypod Reusable Pen

**Comment by richiecroker** [comment]
In the two lists, i'd say all of the first are specials.  For the second list, i'd say the following are:

091101000BBSZDJ | Amargine_Liq Spec 500mg/5ml
0301030S0AABCBC | Theophylline_Liq Spec 60mg/5ml
0407020Q0AAFMFM | Morph Sulf_Gel Spec 1% 10ml Pfs
0401020K0AABHBH | Diazepam_Liq Spec 10mg/5ml (Old)
190202000AABBBB | Individually Formulated Spec CD_
0407010H0AAAVAV | Paracet_Tab Spec Fine Grade 500mg

**Comment by lmfrench** [comment]
Query includes:
All items flagged under dm+d as '6'
The 921 specials from ePACT not flagged by dm+d
Everything from the first list of 'Spec' and those listed by Rich from the second list.

```sql
SELECT 
  FORMAT_DATETIME('%Y-%m',DATETIME(presc.month)) AS month,
  pct, 
  ccg.name AS ccg_name,
  practice,
  prac.name AS practice_name,
  presc.bnf_code,
  bnf_name,
  avail_restrictcd AS dmd_special_flag,
  SUM(items) as items,
  SUM(actual_cost) AS actual_cost
  FROM 
  ebmdatalab.hscic.normalised_prescribing_standard AS presc

LEFT JOIN ebmdatalab.hscic.dmd AS dmd 
ON dmd.bnf_code=presc.bnf_code

LEFT JOIN ebmdatalab.hscic.practices as prac
ON presc.practice=prac.code

LEFT JOIN ebmdatalab.hscic.ccgs as ccg
ON presc.pct=ccg.code

WHERE
month >= '2017-03-01'
AND
(avail_restrictcd='6'
OR
(presc.bnf_code LIKE '0407010H0AAAVAV%')) #other BNF codes from Spec search & EPACT added here
AND
pct IN ('02W','02R','02T')
AND
prac.setting=4

GROUP BY
pct,
ccg_name,
practice,
practice_name,
dmd_special_flag,
bnf_code,
bnf_name,
month

ORDER BY
month,
pct,
practice
```
