### ISSUE TITLE
Exelon patches & exelon capsules

### ISSUE THREAD

**Issue by lmfrench** [ebmdatalab/prescribing-queries#5]
I am trying to find out the prescription of exelon patches against exelon capsules so it would be great if I can get a data extract of the total of all exelon capsules prescribed (1.5mg, 3mg, 4.5mg, 6mg) and also the total of all exelon patches prescribed (9.5mg/24 hours, 4.6mg/24 hours, 13.3mg/24 hours) so that I can compare the prescribing of the two formulations. 

Below is the information: 

Time Period: August 2010 to June 2016 

Group by month 

CCG's: NHS NORTH & WEST READING and NHS SOUTH READING 

Include out of hours and walk-in centres 

Would like to see actual cost as well as number of items

**Comment by lmfrench** [comment]
``` sql
SELECT 
PCT AS CCG, 
name AS CCG_Name,
STRFTIME_UTC_USEC(TIMESTAMP(month),'%B %Y') AS month,  
bnf_code AS BNF_Code, 
bnf_name AS BNF_Name, 
SUM(items) as items, 
SUM(actual_cost) as actual_cost 
FROM ebmdatalab.hscic.prescribing AS presc

LEFT JOIN ebmdatalab.hscic.eccg AS eccg
  ON (org_code=presc.pct)
WHERE 

(bnf_code LIKE '0411000E0BBAAAA' 
OR bnf_code LIKE '0411000E0BBACAC'
OR bnf_code LIKE '0411000E0BBADAD'
OR bnf_code LIKE '0411000E0BBABAB'
OR bnf_code LIKE '0411000E0BBAHAI'
OR bnf_code LIKE '0411000E0BBAFAF'
OR bnf_code LIKE '0411000E0BBAGAG'
)
AND
(PCT = '10N' OR PCT='10W')

GROUP BY
CCG,
CCG_Name,
month,
bnf_code,
bnf_name

ORDER BY
month,
bnf_name
```

**Comment by lmfrench** [comment]
This is the kind of query I think doesn't need checking anymore, there aren't many results but I think that's probably because not much is being prescribed

**Comment by sebbacon** [comment]
This is fine, but I wonder if they really mean Exelon, or if they actually mean Rivastigmine. Especially given what we were talking about the other day -- if generic Rivastigmine patches are prescribed, these will often actually turn out to be Exelon but not marked as such. So just restricting to Exelon is only going to tell you about who is specifically prescribing that brand. I can't imagine that's what they really want.

You could get generics and branded versions of the same presentations by using an underscore as a wildcard, which gives considerably more data (most prescribing seems not to be by brand):

``` sql
SELECT
  PCT AS CCG,
  name AS CCG_Name,
  STRFTIME_UTC_USEC(TIMESTAMP(month),'%B %Y') AS month,
  bnf_code AS BNF_Code,
  bnf_name AS BNF_Name,
  SUM(items) AS items,
  SUM(actual_cost) AS actual_cost
FROM
  ebmdatalab.hscic.prescribing AS presc
LEFT JOIN
  ebmdatalab.hscic.eccg AS eccg
ON
  (org_code=presc.pct)
WHERE
  (bnf_code LIKE '0411000E0__AAAA'
    OR bnf_code LIKE '0411000E0__ACAC'
    OR bnf_code LIKE '0411000E0__ADAD'
    OR bnf_code LIKE '0411000E0__ABAB'
    OR bnf_code LIKE '0411000E0__AHAI'
    OR bnf_code LIKE '0411000E0__AFAF'
    OR bnf_code LIKE '0411000E0__AGAG' )
  AND (PCT = '10N'
    OR PCT='10W')
GROUP BY
  CCG,
  CCG_Name,
  month,
  bnf_code,
  bnf_name
ORDER BY
  month,
  bnf_name
```

Similarly, they may actually not mean only patches or caps, but any prescriptions -- replacing the `OR`s with a single `LIKE '0411000E0%'` gives a further 20 prescriptions (about 4%).

**Comment by lmfrench** [comment]
ok thanks! I will send them with the generics, but will add that as a standard question to ask for future queries where a brand is specified. 

They do want only patches/caps as they were going to compare the prescribing of patches/caps

final query used (only edit is the month so it works with standard sql)

``` sql
SELECT
  PCT AS CCG,
  name AS CCG_Name,
  FORMAT_DATETIME('%B %Y',
    DATETIME(presc.month)) AS month,
  bnf_code AS BNF_Code,
  bnf_name AS BNF_Name,
  SUM(items) AS items,
  SUM(actual_cost) AS actual_cost
FROM
  ebmdatalab.hscic.prescribing AS presc
LEFT JOIN
  ebmdatalab.hscic.eccg AS eccg
ON
  (org_code=presc.pct)
WHERE
  (bnf_code LIKE '0411000E0__AAAA'
    OR bnf_code LIKE '0411000E0__ACAC'
    OR bnf_code LIKE '0411000E0__ADAD'
    OR bnf_code LIKE '0411000E0__ABAB'
    OR bnf_code LIKE '0411000E0__AHAI'
    OR bnf_code LIKE '0411000E0__AFAF'
    OR bnf_code LIKE '0411000E0__AGAG' )
  AND (PCT = '10N'
    OR PCT='10W')
GROUP BY
  CCG,
  CCG_Name,
  month,
  bnf_code,
  bnf_name
ORDER BY
  month,
  bnf_name
```
