### ISSUE TITLE
Request for data on hormones etc

### ISSUE THREAD

**Issue by HelenCEBM** [ebmdatalab/prescribing-queries#54]
BNF codes: 0605010G0, 0803041L0(data for infertility indication), 0605010AB, 0605010I0, 0605010K0, 0605010M0, 0605010D0, 0605010X0, 0604012S0, 0607020D0, 0607020W0, 0607020P0, 0605010N0, 0605010Y0, 0803042P0

Time Period (earliest date August 2010) | earliest date to till date
Grouped monthly/yearly: | Monthly
CCG/GP Practice(s) of Interest | GP practice
Grouped by GP Practice or CCG? | GP Practice
Include non-standard GP Practices? | No
Include Actual Cost? | Yes
Other Information | Include Net Ingredient Cost as well
When do you need the data by? | 23/10/2017

https://docs.google.com/spreadsheets/d/1ZVMotn1U514hSvW1zB91GT49VHUmPiwBOf8vot-bVxQ/edit#gid=1699853238

**Comment by alexwalkerepi** [comment]
```sql
SELECT
  FORMAT_DATETIME('%Y-%m',
    DATETIME(presc.month)) AS month,
  practice,
  bnf_code,
  bnf_name,
  chemical,
  items,
  quantity,
  net_cost,
  actual_cost
FROM
  ebmdatalab.hscic.normalised_prescribing_standard AS presc
LEFT JOIN
  ebmdatalab.hscic.bnf AS bnf
ON
  presentation_code=bnf_code
LEFT JOIN
  ebmdatalab.hscic.practices AS pract
ON
  presc.practice=pract.code
WHERE
  (bnf_code LIKE "0605010G0%"
    OR bnf_code LIKE "0803041L0%"
    OR bnf_code LIKE "0605010AB%"
    OR bnf_code LIKE "0605010I0%"
    OR bnf_code LIKE "0605010K0%"
    OR bnf_code LIKE "0605010M0%"
    OR bnf_code LIKE "0605010D0%"
    OR bnf_code LIKE "0605010X0%"
    OR bnf_code LIKE "0604012S0%"
    OR bnf_code LIKE "0607020D0%"
    OR bnf_code LIKE "0607020W0%"
    OR bnf_code LIKE "0607020P0%"
    OR bnf_code LIKE "0605010N0%"
    OR bnf_code LIKE "0605010Y0%"
    OR bnf_code LIKE "0803042P0%" )
  AND setting=4
ORDER BY
  practice
```
