### ISSUE TITLE
BNF 2.12, 2.5, 6.1

### ISSUE THREAD

**Issue by HelenCEBM** [ebmdatalab/prescribing-queries#58]
BNF Codes | 2.12, 2.5, 6.1 (broken down into the sub chapters below these)
Time Period (earliest date August 2010) | 2013-present
Grouped monthly/yearly: | Monthly
CCG/GP Practice(s) of Interest | Brent, Central London, Ealing, Hammersmith and Fulham, Harrow, Hillingdon, Hounslow, West London
Grouped by GP Practice or CCG? | GP Practice
Include non-standard GP Practices? | Yes
Include Actual Cost? | Yes

https://docs.google.com/spreadsheets/d/1ZVMotn1U514hSvW1zB91GT49VHUmPiwBOf8vot-bVxQ/edit#gid=1699853238

**Comment by alexwalkerepi** [comment]
```sql
SELECT
  FORMAT_DATETIME('%Y-%m',
    DATETIME(presc.month)) AS month,
  practice,
  pct AS ccg,
  SUBSTR(bnf_code, 1, 7) as subpara_code,
  subpara,
  SUM(items) AS items,
  SUM(quantity) AS quantity,
  SUM(net_cost) AS net_cost,
  SUM(actual_cost) AS actual_cost
FROM
  ebmdatalab.hscic.normalised_prescribing_standard AS presc
LEFT JOIN
  ebmdatalab.hscic.bnf AS bnf
ON
  presentation_code=bnf_code
WHERE
  (bnf_code LIKE "0212%"
    OR bnf_code LIKE "0205%"
    OR bnf_code LIKE "0601%")
  AND (pct = "07P"
    OR pct = "09A"
    OR pct = "07W"
    OR pct = "08C"
    OR pct = "08E"
    OR pct = "08G"
    OR pct = "07Y"
    OR pct = "08Y")
  AND
  month >= '2013-01-01'
GROUP BY
  month,
  practice,
  ccg,
  subpara_code,
  subpara
ORDER BY
  practice,
  subpara,
  month
```
